version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - turksat-net

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: turksat-mssql
    environment:
      SA_PASSWORD: "MyPass123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - turksat-net

networks:
  turksat-net: {}
